title: Lucas Cruz
logo: /assets/img/headshot_circle.png
description: Driven by passion for technology and continuous self-learning, I build data solutions that transform data into insights. I thrive on innovation, exploring tools and architectures to solve real problems, improve decision-making, and deliver scalable systems that create a business impact. 
show_downloads: true
theme: jekyll-theme-minimal