title: I'm Lucas Cruz
logo: /assets/img/headshot_circle.png
description: Passionate about technology and continuous learning, I build scalable data solutions that turn data into insights, drive smarter decisions, and solve real business problems through innovation and modern architectures.
show_downloads: true
theme: jekyll-theme-minimal